baseurl = "https://cdiener.com"
languageCode = "en-us"
title = "Christian's website"

pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
    mdlversion = "1.3.0"
    mdltheme = "indigo-red"
