#!/usr/bin/env bash

echo "--- Deploying ---"

msg=$1
if [[ -z "$msg" ]] ; then
    msg="Changes from $(date)"
fi

echo "Minifying static assets..."
css-html-js-minify.py static &> /dev/null

echo "Saving changes..."
git add -A > /dev/null
git commit -am "$msg" > /dev/null
git push

echo "Generating page..."
hugo

echo "Deploying site..."
cd public
git add -A > /dev/null
git commit -am "$msg" > /dev/null
git push

echo "--- done ---"
